//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMap"",
            ""id"": ""f8f7545b-ac2b-4e3d-8bbe-17aa312c7ca4"",
            ""actions"": [
                {
                    ""name"": ""MouseX"",
                    ""type"": ""Value"",
                    ""id"": ""6d444d2b-2ef2-4367-9134-1ab10411ab45"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""Value"",
                    ""id"": ""2568eb20-f46e-462e-8d6f-efe0b269319d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sneak"",
                    ""type"": ""Value"",
                    ""id"": ""2ae0a9d5-2603-4742-956e-7f5366ba9ded"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""20bf0bb4-4e14-4940-b7f2-3b8a9b8aed5e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""48b86e0d-94cc-492a-b2cd-16d5e4f0021a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""daf2032d-11e3-44b2-805d-fbccb51fb2a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabItem1"",
                    ""type"": ""Button"",
                    ""id"": ""1ac33bb4-13e9-4b95-a3a4-6a8af51c67c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabItem2"",
                    ""type"": ""Button"",
                    ""id"": ""4532d491-c4b0-4f58-bf21-7cbc1b2f78aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabItem3"",
                    ""type"": ""Button"",
                    ""id"": ""a0870a7b-e09d-450f-a426-aff9e5195603"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabItem4"",
                    ""type"": ""Button"",
                    ""id"": ""f74080cd-2a17-4dfa-b67d-bb75003cef36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabItem5"",
                    ""type"": ""Button"",
                    ""id"": ""b06564cc-c9b8-44c2-adea-2b6cef0a4651"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""817f0002-d128-40e8-ab95-30d49192a9a1"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79d47d02-9a7a-449f-96c1-74b199ef2369"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3744c6ce-077b-4e0c-a8c5-07496e1f762a"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sneak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0648d465-fbab-4ec9-8b45-71a58f34a5bd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""04b62cdb-667a-4400-96d9-8c9c0fad89aa"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6fbf0a3d-6b81-46a1-aed2-eb9c87aac0bc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""db36a54b-0acf-435e-86d5-c132d2f394a7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d01781b3-dd8f-49e9-a813-c9e3a8c98500"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""da831889-5df3-4c47-a990-553de80bdea8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""144755fd-2cfe-411c-8741-0620027c6529"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95c94d9b-8218-485d-81e5-32d2b48fdb89"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c76c0af-5b36-4687-82a3-6146029b6681"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ebf7097-d35d-4a49-a276-6cdc69c56a94"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a397ed31-e490-4613-af81-e56dd37ff09e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabItem4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b15fd887-8a7b-48a9-bcc9-dad5df08d5de"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabItem5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // PlayerMap
        m_PlayerMap = asset.FindActionMap("PlayerMap", throwIfNotFound: true);
        m_PlayerMap_MouseX = m_PlayerMap.FindAction("MouseX", throwIfNotFound: true);
        m_PlayerMap_MouseY = m_PlayerMap.FindAction("MouseY", throwIfNotFound: true);
        m_PlayerMap_Sneak = m_PlayerMap.FindAction("Sneak", throwIfNotFound: true);
        m_PlayerMap_Movement = m_PlayerMap.FindAction("Movement", throwIfNotFound: true);
        m_PlayerMap_Interact = m_PlayerMap.FindAction("Interact", throwIfNotFound: true);
        m_PlayerMap_UseItem = m_PlayerMap.FindAction("UseItem", throwIfNotFound: true);
        m_PlayerMap_GrabItem1 = m_PlayerMap.FindAction("GrabItem1", throwIfNotFound: true);
        m_PlayerMap_GrabItem2 = m_PlayerMap.FindAction("GrabItem2", throwIfNotFound: true);
        m_PlayerMap_GrabItem3 = m_PlayerMap.FindAction("GrabItem3", throwIfNotFound: true);
        m_PlayerMap_GrabItem4 = m_PlayerMap.FindAction("GrabItem4", throwIfNotFound: true);
        m_PlayerMap_GrabItem5 = m_PlayerMap.FindAction("GrabItem5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMap
    private readonly InputActionMap m_PlayerMap;
    private List<IPlayerMapActions> m_PlayerMapActionsCallbackInterfaces = new List<IPlayerMapActions>();
    private readonly InputAction m_PlayerMap_MouseX;
    private readonly InputAction m_PlayerMap_MouseY;
    private readonly InputAction m_PlayerMap_Sneak;
    private readonly InputAction m_PlayerMap_Movement;
    private readonly InputAction m_PlayerMap_Interact;
    private readonly InputAction m_PlayerMap_UseItem;
    private readonly InputAction m_PlayerMap_GrabItem1;
    private readonly InputAction m_PlayerMap_GrabItem2;
    private readonly InputAction m_PlayerMap_GrabItem3;
    private readonly InputAction m_PlayerMap_GrabItem4;
    private readonly InputAction m_PlayerMap_GrabItem5;
    public struct PlayerMapActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseX => m_Wrapper.m_PlayerMap_MouseX;
        public InputAction @MouseY => m_Wrapper.m_PlayerMap_MouseY;
        public InputAction @Sneak => m_Wrapper.m_PlayerMap_Sneak;
        public InputAction @Movement => m_Wrapper.m_PlayerMap_Movement;
        public InputAction @Interact => m_Wrapper.m_PlayerMap_Interact;
        public InputAction @UseItem => m_Wrapper.m_PlayerMap_UseItem;
        public InputAction @GrabItem1 => m_Wrapper.m_PlayerMap_GrabItem1;
        public InputAction @GrabItem2 => m_Wrapper.m_PlayerMap_GrabItem2;
        public InputAction @GrabItem3 => m_Wrapper.m_PlayerMap_GrabItem3;
        public InputAction @GrabItem4 => m_Wrapper.m_PlayerMap_GrabItem4;
        public InputAction @GrabItem5 => m_Wrapper.m_PlayerMap_GrabItem5;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Add(instance);
            @MouseX.started += instance.OnMouseX;
            @MouseX.performed += instance.OnMouseX;
            @MouseX.canceled += instance.OnMouseX;
            @MouseY.started += instance.OnMouseY;
            @MouseY.performed += instance.OnMouseY;
            @MouseY.canceled += instance.OnMouseY;
            @Sneak.started += instance.OnSneak;
            @Sneak.performed += instance.OnSneak;
            @Sneak.canceled += instance.OnSneak;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @GrabItem1.started += instance.OnGrabItem1;
            @GrabItem1.performed += instance.OnGrabItem1;
            @GrabItem1.canceled += instance.OnGrabItem1;
            @GrabItem2.started += instance.OnGrabItem2;
            @GrabItem2.performed += instance.OnGrabItem2;
            @GrabItem2.canceled += instance.OnGrabItem2;
            @GrabItem3.started += instance.OnGrabItem3;
            @GrabItem3.performed += instance.OnGrabItem3;
            @GrabItem3.canceled += instance.OnGrabItem3;
            @GrabItem4.started += instance.OnGrabItem4;
            @GrabItem4.performed += instance.OnGrabItem4;
            @GrabItem4.canceled += instance.OnGrabItem4;
            @GrabItem5.started += instance.OnGrabItem5;
            @GrabItem5.performed += instance.OnGrabItem5;
            @GrabItem5.canceled += instance.OnGrabItem5;
        }

        private void UnregisterCallbacks(IPlayerMapActions instance)
        {
            @MouseX.started -= instance.OnMouseX;
            @MouseX.performed -= instance.OnMouseX;
            @MouseX.canceled -= instance.OnMouseX;
            @MouseY.started -= instance.OnMouseY;
            @MouseY.performed -= instance.OnMouseY;
            @MouseY.canceled -= instance.OnMouseY;
            @Sneak.started -= instance.OnSneak;
            @Sneak.performed -= instance.OnSneak;
            @Sneak.canceled -= instance.OnSneak;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @GrabItem1.started -= instance.OnGrabItem1;
            @GrabItem1.performed -= instance.OnGrabItem1;
            @GrabItem1.canceled -= instance.OnGrabItem1;
            @GrabItem2.started -= instance.OnGrabItem2;
            @GrabItem2.performed -= instance.OnGrabItem2;
            @GrabItem2.canceled -= instance.OnGrabItem2;
            @GrabItem3.started -= instance.OnGrabItem3;
            @GrabItem3.performed -= instance.OnGrabItem3;
            @GrabItem3.canceled -= instance.OnGrabItem3;
            @GrabItem4.started -= instance.OnGrabItem4;
            @GrabItem4.performed -= instance.OnGrabItem4;
            @GrabItem4.canceled -= instance.OnGrabItem4;
            @GrabItem5.started -= instance.OnGrabItem5;
            @GrabItem5.performed -= instance.OnGrabItem5;
            @GrabItem5.canceled -= instance.OnGrabItem5;
        }

        public void RemoveCallbacks(IPlayerMapActions instance)
        {
            if (m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMapActions @PlayerMap => new PlayerMapActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerMapActions
    {
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnSneak(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnGrabItem1(InputAction.CallbackContext context);
        void OnGrabItem2(InputAction.CallbackContext context);
        void OnGrabItem3(InputAction.CallbackContext context);
        void OnGrabItem4(InputAction.CallbackContext context);
        void OnGrabItem5(InputAction.CallbackContext context);
    }
}
